### ISSUE TITLE
Projects Display Issue

### ISSUE THREAD

**Issue by nixxcode** [robhinds/robhinds.github.io#16]
I can see a similar issue has been mentioned before in issue #10. This one seems to be unrelated.

It would appear that adding projects from several different owners to the github: section causes a problem where only projects from the last listed owner are displayed. (and in some cases, duplicated)

This is from my _config.yml:
```
github:
 - google/brotli
 - nixxcode/jvm-brotli
 - nixxcode/brotli
 - nixxcode/nixxcode.github.io
 - tipsy/javalin
```

And this is the result:
![before_fix](https://user-images.githubusercontent.com/46871088/62542033-e75d6f00-b852-11e9-86ef-3d5b7e326467.PNG)

I was able to track the issue to this line in _includes/jsimports.html:
`<script type="text/javascript" src="./js/jquery.githubRepoWidget.custom.js"></script>`

I was able to fix it by:
- Going to https://github.com/hustcc/GitHub-Repo-Widget.js 
- Downloading GithubRepoWidget.min.js and saving it to the js folder
- Changing the above line to `<script type="text/javascript" src="./js/GithubRepoWidget.min.js"></script>`

Here is the post-fix result:
![after_fix](https://user-images.githubusercontent.com/46871088/62542377-94d08280-b853-11e9-8b89-139017283938.PNG)

Would you like me to submit a pull request with the fix?

**Comment by robhinds** [comment]
Yes, please, @nixxcode that would be great!

**Comment by nixxcode** [comment]
All done.

And thank you for a fantastic CV template! I am setting mine up as we speak. :)

**Comment by robhinds** [comment]
Closing as I finally merged the PR (apologies it took so long!)
