### ISSUE TITLE
How do i remove London, Uk text in page 

### ISSUE THREAD

**Issue by AdhithAdhi** [robhinds/robhinds.github.io#34]
How do I remove London, Uk text on the page?
I don't know about this language but I forked the project and changed it but I noticed that am getting a London, Uk text on the page.

**Comment by robhinds** [comment]
Ah yeah, thats hardcoded at the moment - you can just change the text in this file on your branch: https://github.com/robhinds/robhinds.github.io/blob/master/_includes/footer.html

I will add that on the list of possible data to move to config

**Comment by AdhithAdhi** [comment]
thanks fixed it, I didn't look deep into the code that's my bad
