### ISSUE TITLE
ISSUSE WITH GITHUB PROJECT SHORT DISCRIPTION

### ISSUE THREAD

**Issue by AdhithAdhi** [robhinds/robhinds.github.io#35]
am having some issues with github short description about project. it is showing "null" as description. 
but if it's your project its showing description but not with mine.
screenshot attached
![Screenshot from 2021-06-17 22-09-22](https://user-images.githubusercontent.com/57002396/122438777-b3a81000-cfb8-11eb-89cb-cabe144de9f8.png)

**Comment by robhinds** [comment]
Ah those projects don't seem to have a description e.g. https://github.com/AdhithAdhi/DefendTheInvaders in the right hand column, under About you will see it says there are no descriptions.

I should fix it so it handles the null more gracefully, but an interim fix you can add a description to those projects on GitHub.  If you test with this project, for example: https://github.com/AdhithAdhi/AdhithAdhi, you should get the description pulled down.

**Comment by AdhithAdhi** [comment]
sorry my bad i thought its reading from readme file.
 i will close the issue.
Checkout my profile site with your code https://adhithadhi.github.io/

**Comment by robhinds** [comment]
Cool, like what you have done with it - looks good 👍
